version: '3'
services:

  consumer:
    image: consumer
    depends_on:
      - rabbitmq
    deploy:
      replicas: 10
    networks:
      - bigdata

  daas:
    image: daas
    container_name: daas
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - bigdata

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bigdata

networks:
  bigdata:
    name: bigdata-network
    external: true